name: Run R Script

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          install.packages("tidyverse")
          install.packages("jsonlite") # if needed for API calls
          install.packages("DatawRappr") # if needed for API calls
        shell: Rscript {0}

      - name: Run R script
        env: 
          API_KEY: ${{ secrets.DW_API_KEY }}
          CHART_KEY: ${{ secrets.CHART_KEY }}
        run: Rscript measles-scraper.R
